module.exports = {
  libs: [
    './themes/default/assets/plugins/formvalidation/js/formValidation.popular.min.js',
    './themes/default/assets/plugins/formvalidation/js/framework/bootstrap.min.js',
    './themes/default/assets/plugins/slimScroll/jquery.slimscroll.min.js',
    './themes/default/assets/plugins/input-mask/jquery.inputmask.js',
    './themes/default/assets/plugins/input-mask/jquery.inputmask.date.extensions.js',
    './themes/default/assets/plugins/datatables/datatables.min.js',
    './themes/default/assets/plugins/select2/select2.full.min.js',
    './themes/default/assets/plugins/fastclick/fastclick.min.js',
    './themes/default/assets/plugins/redactor/redactor.min.js',
    './themes/default/assets/plugins/velocity/velocity.min.js',
    './themes/default/assets/plugins/velocity/velocity.ui.min.js',
    './themes/default/assets/bootstrap/js/bootstrap.min.js',
    './themes/default/assets/plugins/icheck/icheck.min.js',
    './themes/default/assets/dev/js/parse-track-data.js',
    './themes/default/assets/plugins/socket.io.min.js',
    './themes/default/assets/dev/js/jquery-ui.min.js',
    './themes/default/assets/dev/js/hideseek.min.js',
    './themes/default/assets/dev/js/common-libs.js',
    './themes/default/assets/dev/js/app.min.js',
  ],
  js: ['./themes/default/assets/dev/js/pages/all.js', './themes/default/assets/dev/js/custom.js'],
  posjs: ['./themes/default/assets/dev/js/pos.js'],
  purchase: ['./themes/default/assets/dev/js/pages/purchases.js'],
  css: [
    './themes/default/assets/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css',
    './themes/default/assets/plugins/font-awesome/css/font-awesome.css',
    './themes/default/assets/plugins/datatables/datatables.min.css',
    './themes/default/assets/bootstrap/css/bootstrap.min.css',
    './themes/default/assets/plugins/select2/select2.min.css',
    './themes/default/assets/plugins/icheck/skins/square/blue.css',
    './themes/default/assets/plugins/redactor/redactor.css',
    './themes/default/assets/dev/css/jquery-ui.css',
    './themes/default/assets/dev/css/AdminLTE.min.css',
    './themes/default/assets/dev/css/skins/_all-skins.min.css',
    './themes/default/assets/dev/css/custom.css',
  ],
  img: ['./themes/default/assets/plugins/icheck/skins/square/blue.png', './themes/default/assets/plugins/icheck/skins/square/blue@2x.png'],
  fonts: [
    './themes/default/assets/dev/fonts/**/*',
    './themes/default/assets/bootstrap/fonts/**/*',
    './themes/default/assets/plugins/font-awesome/fonts/**/*',
  ],
  dist: {
    js: './themes/default/assets/dist/js/',
    css: './themes/default/assets/dist/css/',
    img: './themes/default/assets/dist/css/',
    fonts: './themes/default/assets/dist/fonts/',
  },
};
